// Generated by Wrangler by running `wrangler types`

interface Env {
	DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1287074116788031489/SFI_J27nP99MbNPn5zd7-FoGTKyXOXXHN3kHjvuCQlXVr6YOS02UlmCXIxPvtYN2H-nI";
}
